#!/bin/bash
yum update -y
amazon-linux-extras install nginx1.12
systemctl enable nginx
systemctl start nginx


#2 for version 2 

#!/bin/bash
yum update -y
amazon-linux-extras install nginx1.12
chkconfig nginx on
cd /usr/share/nginx/html
chmod o+w /usr/share/nginx/html
rm index.html
wget https://raw.githubusercontent.com/awsdevopsteam/ngniex/master/index.html
wget https://raw.githubusercontent.com/awsdevopsteam/ngniex/master/ryu.jpg
service nginx start